---
# tasks file for role_install_splunk_windows
- name: "Check | Splunk Agent"
  win_service:
    name: SplunkForwarder
  register: splunk_service_info

- name: "Splunk | Already Installed"
  set_fact:
    splunk_msg: "Splunk Agent is already installed"
  when: splunk_service_info.exists == true

- name: "Splunk | Not Installed"
  include_tasks: install_splunk.yml
  when: splunk_service_info.exists == false

- debug:
    msg: "{{ splunk_msg }}"

- name: "delete | splunk files"
  win_file:
    path: "{{ splunk_temp_folder_windows }}"
    state: absent
  ignore_errors: true
